# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://bitbucket.org/doing-lab/foodlenssdk-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'FoodLensTestApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'FoodLens', '2.0.25'
  # When you want to use FoodLens SDK V1, Use below
  #pod 'FoodLens'. '0.1.15'

  # Pods for FoodLensTestApp

  target 'FoodLensTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodLensTestAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
