# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'FoodLensTestApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'FoodLens', '~> 2.6.0'
  # When you want to use FoodLens SDK V1, Use below

  # Pods for FoodLensTestApp

  target 'FoodLensTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodLensTestAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
